class_path: gnn_tracking.training.classification.NodeClassifierModule
init_args:
  model:
    class_path: gnn_tracking.models.graph_construction.GraphConstructionFCNN
    init_args:
      alpha: 0.6
      depth: 6
      hidden_dim: 256
      in_dim: 14
      out_dim: 2
      classification: true
  loss_fct:
    class_path: gnn_tracking.metrics.losses.classification.CEL
    init_args:
      weight: [0.9348, 0.0652]
  optimizer:
    class_path: torch.optim.Adam
    init_args:
      lr: 0.001
  scheduler:
    class_path: torch.optim.lr_scheduler.ExponentialLR
    init_args:
      gamma: 0.985